### ISSUE TITLE
Support for GeoTiff

### ISSUE THREAD

**Issue by HeadClot** [MacroPolo/real-terrain#2]
Would it be possible to support the Geo Tiff File format?

I know that GDAL supports this format. So it would just be a matter of having the real terrain tool accept the format.

I am asking this as I mostly use [this](http://dwtkns.com/srtm/) site to grab my terrain. :)

**Comment by MacroPolo** [comment]
Yeah I should be able to do that.

**Comment by MacroPolo** [comment]
Ok, I've simplified the conversion so you should be able to use GeoTiff for input now. Same method as before: `python real-terrain.py test.tif`
